# config files
---
$default$:
  _leaf:
    base_url: "https://www.google.com/search"
    q_params: "q"
g:
  _leaf:
    base_url: "https://www.google.com/search"
    q_params: "q"
nus:
  _default: "https://www.nus.edu.sg/"
  lum:
    _default: "https://luminus.nus.edu.sg/dashboard/"
    _leaf:
      base_url: "https://luminus.nus.edu.sg/modules/{{ modules }}"
      docstring: "navigates to modules in luminus"
      type: "path"
      modules:
        cs2100: "edde22e8-413b-45a4-b2c5-9a948c23689d"
        cs2101: "895148ac-63ef-4044-acf4-1ec29068d9e0"
bib:
  _leaf:
    base_url: "https://alkitab.sabda.org/bible.php"
    q_params:
      - "book"
      - "chapter"
cf:
  _leaf:
    base_url: "https://dash.cloudflare.com/"
doc:
  py:
    _leaf:
      base_url: "https://docs.python.org/3/search.html"
      q_params: "q"
  mdn:
    _leaf:
      base_url: "https://developer.mozilla.org/en-US/search"
      q_params: "q"
ibank:
  ocbc:
    _leaf:
      base_url: "https://internet.ocbc.com/internet-banking"
  dbs:
    _leaf:
      base_url: "https://internet-banking.dbs.com.sg"
libgen:
  _leaf:
    base_url: "http://libgen.rs/search.php"
    q_params: "req"
so:
  _leaf:
    base_url: "https://stackoverflow.com/search"
    q_params: "q"
soc:
  claim:
    _leaf:
      base_url: "https://mysoc.nus.edu.sg/~tssclaim/tutor/index.php"
  curr:
    _leaf:
      base_url: "https://www.comp.nus.edu.sg/cugresource/per-cohort/cs/cs-19-20/"
  print:
    _leaf:
      base_url: "https://mysoc.nus.edu.sg/app/eprint/forms/quota.php"
  sched:
    _leaf:
      base_url: "https://www.comp.nus.edu.sg/cugresource/soc-sched/"
yt:
  _leaf:
    base_url: "https://www.youtube.com/results"
    q_params: "search_query"
