# config files
---
$default$:
  base_url: 'https://www.google.com/search'
  q_params: 'q'
  docstring: 'does a google search'
g:
  base_url: 'https://www.google.com/search'
  docstring: 'does a google search'
  q_params: 'q'
cf: 'https://dash.cloudflare.com/'
gh:
  base_url: 'https://github.com/{{ acc }}/{{ repo }}'
  docstring: 'does a github search.'
  acc:
    home: 'benclmnt'
yt:
  _leaf: 'https://www.youtube.com'
  v:
    base_url: 'https://www.youtube.com/results'
    q_params: 'search_query'
    docstring: 'does a youtube search'
tr:
  en:
    base_url: 'https://translate.google.com/?sl=auto&tl=en'
    q_params: 'text'
    docstring: 'does a translation to english'
